all:
  children:
    kubernetes_cluster:
      vars:
        ansible_user: "{{ ansible_username }}"
        ansible_ssh_private_key_file: "{{ ansible_key_file_path }}"
      children:
        control_plane:
          hosts:
            cp:
              ansible_host: "{{ control_plane_ip }}"
        workers:
          hosts:
            worker-1:
              ansible_host: "{{ worker_1_ip }}"
            worker-2:
              ansible_host: "{{ worker_2_ip }}"